In [28]:
import numpy as np

# 1 - transpose() 
# transpose根据shape进行变换，

# 对于二维数组，相当于转置
a = np.array([[1,2,3], [4,5,6], [6,7,8]])
print(a)
print(a.transpose())
print(a.transpose(1, 0))
print(a.transpose((0, 1)))

[[1 2 3]
 [4 5 6]
 [6 7 8]]
[[1 4 6]
 [2 5 7]
 [3 6 8]]
[[1 4 6]
 [2 5 7]
 [3 6 8]]
[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [49]:
# 对于多维矩阵，transpose()根据shape变换
# 比如数字4的索引为(0,1,0)，原始shape(0,1,2)经transpose(1,0,2)变为(1,0,0)

arr = np.arange(24).reshape(2,3,4)
print(arr)
print('---------------------------')
print(arr.transpose(1,0,2))
print('---------------------------')
print(arr.transpose((2,0,1)))
print('---------------------------')
print(arr.transpose(2,0,1))


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
---------------------------
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
---------------------------
[[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]
---------------------------
[[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]


In [51]:
# 2 - dot  数组的点积
a1 = np.array([1,2,3])
a2 = np.array([1,2,3])
print(np.dot(a1, a2)) 

14
