In [3]:
# 批量梯度下降BGD、随机梯度下降SGD实现
import numpy as np 
import random

# def batchGradientDescent(x, y, thata, alpha, a, maxInteration):
 
def BGD(x, y, theta, alpha, m, maxInteration):
    x_train = x.transpose()
    for i in range(0, maxInteration):
        hypothesis = np.dot(x, theta)
        # 损失函数
        loss = hypothesis - y
        # 下降梯度
        gradient = np.dot(x_train, loss) / m
        # 求导之后得到theta
        theta = theta - alpha * gradient
    return theta
 
 
def SGD(x, y, theta, alpha, m, maxInteration):
    data = []
    for i in range(4):
        data.append(i)
    x_train = x.transpose()
    for i in range(0, maxInteration):
        hypothesis = np.dot(x, theta)
        # 损失函数
        loss = hypothesis - y
        # 选取一个随机数
        index = random.sample(data, 1)
        index1 = index[0]
        # 下降梯度
        gradient = loss[index1] * x[index1]
        # 求导之后得到theta
        theta = theta - alpha * gradient
    return theta
 
 
def main():
    trainData = np.array([[1, 4, 2], [2, 5, 3], [5, 1, 6], [4, 2, 8]])
    trainLabel = np.array([19, 26, 19, 20])
    print(trainData)
    print(trainLabel)
    m, n = np.shape(trainData)
    theta = np.ones(n)
    print(theta.shape)
    maxInteration = 500
    alpha = 0.01
    theta1 = BGD(trainData, trainLabel, theta, alpha, m, maxInteration)
    print(theta1)
    theta2 = SGD(trainData, trainLabel, theta, alpha, m, maxInteration)
    print(theta2)
    return
 
 
if __name__ == "__main__":
   main()

[[1 4 2]
 [2 5 3]
 [5 1 6]
 [4 2 8]]
[19 26 19 20]
(3,)
[ 2.80558885  3.98995956  0.12649808]
[ 2.82045906  3.9813337   0.14765516]
